Add Hour Name
yaa110/go-persian-calendar pull request #22
Opened 2022-07-20 12:52 UTC by mehditeymorian

hour name functionality returns the name of that part of the day based on the 0-23 hour value.
[0,3)   -> midnight
[3,6)   -> dawn
[6,9)  -> morning
[9,12)  -> before noon
[12,15) -> noon
[15,18) -> afternoon
[18,21) -> evening
[21,24) -> night

2022-07-22 14:25 UTC, yaa110 requested changes
خیلی ممنون از مشارکت شما

2022-07-22 14:25 UTC, yaa110 commented on ptime.go
> +var hourNames = []string{
لطفا به جای تعریف []string یک type جدید تعریف کنید و از آن برای خروجی استفاده کنید تا نیاز به ترجمه نباشه:
```go
type DayTimes int

const (
    Midnight DayTimes = iota
    // ...
)

func (t Time) DayTime() DayTimes {
	return DayTimes(t.hour / 3)
}
```

2022-07-23 05:05 UTC, mehditeymorian commented on ptime.go
> +var hourNames = []string{
تایپ DayTime رو اضافه کردم. اما اسم ها رو حذف نکردم چون داخل format استفاده میشه.

2022-07-23 08:58 UTC, yaa110 approved these changes

2022-07-23 08:58 UTC, merged